version: '3'

services:

  etcd:
    image: "quay.io/coreos/etcd:v3.2"
    command: "etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  kubernetes:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.9.2"
    depends_on:
      - "etcd"
    command: "/hyperkube apiserver --insecure-bind-address=0.0.0.0 --etcd-servers=http://etcd:2379 --service-cluster-ip-range=10.0.0.0/16"
    ports:
      - 8080:8080

  controller-manager:
    image: "gcr.io/google-containers/hyperkube-amd64:v1.9.2"
    depends_on:
      - "kubernetes"
    command: "/hyperkube controller-manager --master=http://kubernetes:8080"

  test:
    depends_on:
      - "kubernetes"
    build: .
    command: [
      "/bin/sh",
      "-c",
      "sleep 365d"
    ]
    environment:
      - KUBECONFIG=/experiments/resources/kubeconfig
