apiVersion: "ml.intel.com/v1"
kind: Experiment
metadata:
  name: {{crd_name}}
  namespace: demo
spec:
  jobSpec:
    template:
      spec:
        containers:
        - name: train
          image: {{img}}
          command: ["job.py"]
        restartPolicy: Never
    backoffLimit: 4
